apiVersion: v1
kind: Service
metadata:
  name: hospital-backend
  namespace: num
spec:
  type: NodePort
  selector:
    app: hospital-backend
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
    nodePort: 31000